services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.149.0@sha256:0fba96233274f6d665ac8831ad99dfe6479a9a20459f6e2719c0d20945773b46
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command:
      - '--config=/etc/otel/config.yaml'
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension     - loki
    depends_on:
      - jaeger-collector
      - loki
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.76.0@sha256:429a60eedb3bb25aaf5500d8b4ab11ae7c85250bb1afbdbbbd30b4b8ba01918a
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
      - "--collector.otlp.grpc.host-port=:4317"
      - "--collector.otlp.http.host-port=:4318"
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - '4317'
      - '4318'
    restart: on-failure
    depends_on:
      - cassandra-schema
  cassandra:
    image: cassandra:5.0.7@sha256:1adee7ef220ce93aa1c06ba042ac80d6aca90ee8c3268cc2971120fa6fb64b0a
  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:2.16.0@sha256:c1e64a4a44c93a0d769a80dc30a73232ace2a37b52d4387acd778f24ec45d307
    depends_on:
      - cassandra
  jaeger-query:
    image: jaegertracing/jaeger-query:1.76.0@sha256:fc9f1552ec570f5bfae055c149bd67d83b936371f1947ff503127bb02204295e
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    ports:
      - '16686:16686'
      - '16687:16687'
    restart: on-failure
    depends_on:
      - cassandra-schema
  prometheus:
    image: prom/prometheus:v3.11.0@sha256:dda13e28bf95a5e5ca5b8ed56852006094c1c8e8871d9c9dbeed30aa6e55271f
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --web.enable-otlp-receiver --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:3.7.1@sha256:73e905b51a7f917f7a1075e4be68759df30226e03dcb3cd2213b989cc0dc8eb4
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana:12.4.2@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana:/etc/grafana/provisioning
  pyrra-api:
    image: ghcr.io/pyrra-dev/pyrra:v0.9.5@sha256:4382ed184a02e3d30bfea94c504e9e6eac333426478b255218dd23fb73e0a5c2
    container_name: pyrra_api
    restart: always
    command:
      - api
      - --prometheus-url=http://prometheus:9090
      - --prometheus-external-url=http://localhost:9090
      - --api-url=http://pyrra-filesystem:9444
    ports:
      - "9099:9099"
  pyrra-filesystem:
    image: ghcr.io/pyrra-dev/pyrra:v0.9.5@sha256:4382ed184a02e3d30bfea94c504e9e6eac333426478b255218dd23fb73e0a5c2
    user: root
    container_name: pyrra_filesystem
    restart: always
    command:
      - filesystem
      - --prometheus-url=http://prometheus:9090
    volumes:
      - ./pyrra:/etc/pyrra
      - prometheus_pyrra:/etc/prometheus/pyrra
volumes:
  prometheus-data:
  prometheus_pyrra: {}
