services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.150.1@sha256:a516c26968aa1feb5e5fc0562e3338ea13755cb4f373603226bcc4e276374ad0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command:
      - '--config=/etc/otel/config.yaml'
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension     - loki
    depends_on:
      - jaeger-collector
      - loki
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.76.0@sha256:429a60eedb3bb25aaf5500d8b4ab11ae7c85250bb1afbdbbbd30b4b8ba01918a
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
      - "--collector.otlp.grpc.host-port=:4317"
      - "--collector.otlp.http.host-port=:4318"
    environment:
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - '4317'
      - '4318'
    restart: on-failure
    depends_on:
      - cassandra-schema
  cassandra:
    image: cassandra:5.0.8@sha256:ede1decb2dd2dd8f2bb58ea21d981ee2d42bece44a7ca0dd70d1aa3fcee8bc64
  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:2.17.0@sha256:bc5b40b01ded28bc8a2e2eb8f5a7f0c4380e3171564b7d003be70cfbda662cf0
    depends_on:
      - cassandra
  jaeger-query:
    image: jaegertracing/jaeger-query:1.76.0@sha256:fc9f1552ec570f5bfae055c149bd67d83b936371f1947ff503127bb02204295e
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    ports:
      - '16686:16686'
      - '16687:16687'
    restart: on-failure
    depends_on:
      - cassandra-schema
  prometheus:
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --web.enable-otlp-receiver --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:3.7.1@sha256:73e905b51a7f917f7a1075e4be68759df30226e03dcb3cd2213b989cc0dc8eb4
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana:/etc/grafana/provisioning
  pyrra-api:
    image: ghcr.io/pyrra-dev/pyrra:v0.10.0@sha256:e0c1300c32ec80790655de721d436af5594c1298c4a4fc5da211d6303c40c844
    container_name: pyrra_api
    restart: always
    command:
      - api
      - --prometheus-url=http://prometheus:9090
      - --prometheus-external-url=http://localhost:9090
      - --api-url=http://pyrra-filesystem:9444
    ports:
      - "9099:9099"
  pyrra-filesystem:
    image: ghcr.io/pyrra-dev/pyrra:v0.10.0@sha256:e0c1300c32ec80790655de721d436af5594c1298c4a4fc5da211d6303c40c844
    user: root
    container_name: pyrra_filesystem
    restart: always
    command:
      - filesystem
      - --prometheus-url=http://prometheus:9090
    volumes:
      - ./pyrra:/etc/pyrra
      - prometheus_pyrra:/etc/prometheus/pyrra
volumes:
  prometheus-data:
  prometheus_pyrra: {}
